name: Canary

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

env:
    SKIP_RELEASE: "yes"
    SIGNING_KEYSTORE_FILE: ./secrets/signing_key.jks
    OUTPUT_DIR: ./dist

jobs:
    canary-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: npm

            - uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  cache: gradle

            - name: 🚧 Do prerequisites
              run: npm ci

            - name: 🔢 Get version
              id: app_version
              run: echo "version=$(npm run --silent version:print-canary)" >> $GITHUB_OUTPUT

            - name: 🔎 Check for release
              run: |
                  last_tag=$(npm run --silent git:latest-tag)
                  echo "SKIP_RELEASE=$(npm run --silent git:no-affects-app-yn -- $last_tag)" >> $GITHUB_ENV
              env:
                  TAG_NAME: v${{ steps.app_version.outputs.version }}

            - name: 🔨 Generate certificate
              if: env.SKIP_RELEASE == 'no'
              run: |
                  mkdir -p $(dirname $SIGNING_KEYSTORE_FILE)
                  echo $SIGNING_KEYSTORE_FILE_CONTENT | base64 -di > $SIGNING_KEYSTORE_FILE
              env:
                  SIGNING_KEYSTORE_FILE_CONTENT: ${{ secrets.SIGNING_KEYSTORE_FILE }}

            - name: 🔨 Build assets
              if: env.SKIP_RELEASE == 'no'
              run: |
                  npm run prebuild
                  chmod +x ./gradlew
                  ./gradlew assembleCanary
                  ./gradlew bundleCanary
                  npm run postbuild
              env:
                  APP_BUILD_TYPE: canary
                  APP_VERSION_NAME: ${{ steps.app_version.outputs.version }}
                  SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
                  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

            - name: 🚀 Upload assets
              if: env.SKIP_RELEASE == 'no'
              uses: ncipollo/release-action@v1
              with:
                  tag: v${{ steps.app_version.outputs.version }}
                  artifacts: ${{ env.OUTPUT_DIR }}/*
                  body: "Refer [commits of v${{ steps.app_version.outputs.version }}](https://github.com/zyrouge/symphony/commits/v${{ steps.app_version.outputs.version }}) for the changes."
                  generateReleaseNotes: false
                  allowUpdates: true
                  artifactErrorsFailBuild: true

            - name: 🔖 Was Release skipped?
              if: env.SKIP_RELEASE == 'yes'
              run: echo "Skipping since tag $TAG_NAME already exists"
              env:
                  TAG_NAME: v${{ steps.app_version.outputs.version }}
