name: i18n Summary

on:
    push:
        branches:
            - main
        paths:
            - .phrasey/**
            - i18n/**
    pull_request_review:
        types:
            - submitted
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    i18n-summary:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request_review' || github.event.review.state == 'approved'

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "18.13.0"
                  cache: npm

            - name: 🏗️  Prerequisites
              run: npm install

            - name: 🔨 Build
              run: npm run i18n:summary

            - name: 🚀 Push summary files
              if: github.event_name != 'pull_request_review'
              uses: zyrouge/gh-push-action@v1
              with:
                  directory: phrasey-dist
                  branch: i18n-summary
                  checkout-orphan: true
                  force: true

            - name: 💬 Comment summary
              if: github.event_name == 'pull_request_review'
              uses: actions/github-script@v7
              with:
                  script: |
                      const content = require("fs").readFileSync("phrasey-dist/README.md", "utf-8");
                      github.rest.issues.createComment({
                         issue_number: context.issue.number,
                         owner: context.repo.owner,
                         repo: context.repo.repo,
                         body: content,
                      });
